### ISSUE TITLE
CASHIER validation

### ISSUE THREAD

**Issue by xuan33333** [TanJeeSchuan/OOPTAssignment#11]
1. new sales -> payment type -> option（1/2）  *1或2以外的都默认2
2. new sales -> payment type -> installment -> installment payment  -> option （1/2）
3. new customer -> select role -> option（1/2）

**Comment by TanJeeSchuan** [comment]
new sales -> payment type -> option（1/2） *1或2以外的都默认2            ✅

new sales -> payment type -> installment -> installment payment -> option （1/2）  ✅

new customer -> select role -> option（1/2）         ✅
