### ISSUE TITLE
Selection(int) cannot handle character

### ISSUE THREAD

**Issue by xuan33333** [TanJeeSchuan/OOPTAssignment#13]

**Comment by TanJeeSchuan** [comment]
怎样讲？

**Comment by xuan33333** [comment]
![image](https://github.com/TanJeeSchuan/OOPTAssignment/assets/142018684/c10d2dd8-08f4-46f2-9208-2027e109214f)

**Comment by TanJeeSchuan** [comment]
这个好像没办法喔，要很多 try catch

**Comment by TanJeeSchuan** [comment]
![Screenshot 2023-09-22 152922](https://github.com/TanJeeSchuan/OOPTAssignment/assets/89920999/f7d0aee0-b1f0-4dfb-99b3-dae7d7fd5aed)
@wannnnnnnn006 author
