### ISSUE TITLE
sales quantity 

### ISSUE THREAD

**Issue by xuan33333** [TanJeeSchuan/OOPTAssignment#18]
![image](https://github.com/TanJeeSchuan/OOPTAssignment/assets/142018684/1d8e18ab-61ed-4c60-bdc3-b18393b43ef8)
quantity没有立刻update，会超过本来的quantity

**Comment by TanJeeSchuan** [comment]
![Screenshot 2023-09-22 083257](https://github.com/TanJeeSchuan/OOPTAssignment/assets/89920999/0b7e66ab-2047-4968-8d8f-d7458035be5c)
