### ISSUE TITLE
add user string issue

### ISSUE THREAD

**Issue by xuan33333** [TanJeeSchuan/OOPTAssignment#28]
![WhatsApp 图像 2023-09-25 于 22 14 35](https://github.com/TanJeeSchuan/OOPTAssignment/assets/142018684/e631cce9-e30e-428c-927c-12658d3028fd)
![image](https://github.com/TanJeeSchuan/OOPTAssignment/assets/142018684/ef6f9085-e12b-4121-8447-247b665635f9)
scan只scan到[space]那边，[space]后面的input就跳去下面的了

**Comment by TanJeeSchuan** [comment]
sc.next() 换去 sc.nextLine() 了
