### ISSUE TITLE
Validation modify customer

### ISSUE THREAD

**Issue by xuan33333** [TanJeeSchuan/OOPTAssignment#30]
![image](https://github.com/TanJeeSchuan/OOPTAssignment/assets/142018684/4b0aca68-b0ef-41a3-85c3-ee2111a61499)
MANAGEMENT: modify customer

**Comment by TanJeeSchuan** [comment]
![Screenshot 2023-09-26 104131](https://github.com/TanJeeSchuan/OOPTAssignment/assets/89920999/bc9b6fcc-0ef8-4dea-9fc9-9f013420eccc)
