### ISSUE TITLE
validation in customer

### ISSUE THREAD

**Issue by wannnnnnnn006** [TanJeeSchuan/OOPTAssignment#31]
![WhatsApp Image 2023-09-25 at 11 26 35 PM](https://github.com/TanJeeSchuan/OOPTAssignment/assets/116255048/ef469222-2b27-4812-8958-0238979cfd87)

**Comment by TanJeeSchuan** [comment]
Issue in Tools/objectSelection

**Comment by TanJeeSchuan** [comment]
![Screenshot 2023-09-26 100437](https://github.com/TanJeeSchuan/OOPTAssignment/assets/89920999/b9b104f1-e0df-4f2c-aa60-d8673c2ac472)
