### ISSUE TITLE
Lack of Modify Message in customer & inventory management

### ISSUE THREAD

**Issue by xuan33333** [TanJeeSchuan/OOPTAssignment#33]
![image](https://github.com/TanJeeSchuan/OOPTAssignment/assets/142018684/8784becb-876c-4182-ada8-21b3179500df)

**Comment by TanJeeSchuan** [comment]
![Screenshot 2023-09-26 085221](https://github.com/TanJeeSchuan/OOPTAssignment/assets/89920999/641b75a4-7f91-408d-b772-3b876b9132f6)
![Screenshot 2023-09-26 094103](https://github.com/TanJeeSchuan/OOPTAssignment/assets/89920999/35f2df0f-e826-4125-bda5-e48d2ebf58a7)
